version: 2

git:
  tag_sort: -version:creatordate

before:
  hooks:
    - go mod download

builds:
  - id: "cbdcd-darwin-amd64"
    main: ./cmd/cbdcd
    binary: bin/cbdcd
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=cbdc -X github.com/cosmos/cosmos-sdk/version.AppName=cbdcd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
  - id: "cbdcd-darwin-arm64"
    main: ./cmd/cbdcd
    binary: bin/cbdcd
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=cbdc -X github.com/cosmos/cosmos-sdk/version.AppName=cbdcd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
  - id: "cbdcd-linux-amd64"
    main: ./cmd/cbdcd
    binary: bin/cbdcd
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=cbdc -X github.com/cosmos/cosmos-sdk/version.AppName=cbdcd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
  - id: "cbdcd-linux-arm64"
    main: ./cmd/cbdcd
    binary: bin/cbdcd
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=cbdc -X github.com/cosmos/cosmos-sdk/version.AppName=cbdcd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
  - id: "cbdcd-windows"
    main: ./cmd/cbdcd
    binary: bin/cbdcd
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=cgo
      - -buildmode=exe
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=cbdc -X github.com/cosmos/cosmos-sdk/version.AppName=cbdcd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - cbdcd-darwin-amd64
      - cbdcd-darwin-arm64
      - cbdcd-windows
      - cbdcd-linux-amd64
      - cbdcd-linux-arm64

checksum:
  name_template: 'checksums.txt'