name: "Branch"

on:
  push:
    branches:
      - main
      - honduras

jobs:
  build-docker:
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
    with:
      push: true
      tag: ${{ github.sha }}
      target: release