name: "Release"

on:
  workflow_dispatch:
    inputs:
      commit_branch:
        description: The branch or the commit sha to push tag to
        required: true
      tag:
        description: The tag of the release (vX.Y.Z)
        required: true

jobs:
  build-docker:
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
    with:
      tag: ${{ github.event.inputs.tag }}
      push: true
      target: release

  release:
    name: Github release
    needs: [ build-docker ]
    if: ${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate Github release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          target_commitish: ${{ github.event.inputs.commit_branch }}